import sys
import unittest
from unittest.mock import MagicMock, patch

# --- Dependency Injection Mocking (Only if missing) ---
# This allows running tests in environments where dependencies are not installed.
# In a proper CI environment, these should be handled by standard mocking or integration tests.

try:
    import pydantic
except ImportError:
    # Mock pydantic essentials if missing
    mock_pydantic = MagicMock()
    # Create a dummy class that mimics BaseModel behavior for inheritance
    class MockBaseModel:
        pass
    mock_pydantic.BaseModel = MockBaseModel
    mock_pydantic.Field = lambda *args, **kwargs: None
    mock_pydantic.SecretStr = MagicMock()
    sys.modules["pydantic"] = mock_pydantic

try:
    import github
except ImportError:
    # Mock github essentials if missing
    sys.modules["github"] = MagicMock()
    sys.modules["github.GithubException"] = MagicMock()

# Import module under test
from studio.utils.jules_client import JulesGitHubClient, TaskPayload, TaskPriority

class TestJulesGitHubClient(unittest.TestCase):
    def setUp(self):
        # Mock Github client initialization
        # We need to mock the SecretStr if pydantic is real or mocked
        self.mock_github_token = MagicMock()
        # Ensure get_secret_value returns a string
        self.mock_github_token.get_secret_value.return_value = "dummy-token"

        # We also need to ensure Github class is mocked during instantiation
        # If github module is present, we patch it. If not, we already mocked it in sys.modules
        # But wait, JulesGitHubClient imports Github inside the class or module level?
        # It does: `from github import Github ...`

        # If github was real, we need to patch it.
        # If github was mocked via sys.modules, we can configure the mock.

        if 'github' in sys.modules and isinstance(sys.modules['github'], MagicMock):
             self.client = JulesGitHubClient(self.mock_github_token, "test-repo", "test-jules")
        else:
             # Use patch for real github module
             with patch('studio.utils.jules_client.Github') as MockGithub:
                 self.client = JulesGitHubClient(self.mock_github_token, "test-repo", "test-jules")

    def test_construct_issue_body_full(self):
        # Create a mock payload with all fields populated
        payload = MagicMock()
        payload.task_id = "TKT-101"
        payload.intent = "Fix the bug"
        payload.context_files = {"file1.py": "Description 1", "file2.py": "Description 2"}
        payload.relevant_logs = "Error log details"
        payload.constraints = ["Do TDD", "Avoid regression"]

        # If TaskPayload is a real Pydantic model, we can still pass a MagicMock that bas attributes.
        # Or we can instantiate TaskPayload if pydantic is available.
        # For simplicity and isolation, we use the mock payload.

        body = self.client._construct_issue_body(payload)

        # Assertions
        self.assertIn("@test-jules **Action Required**", body)
        self.assertIn("### 🎯 Intent\nFix the bug", body)
        self.assertIn("**Task ID:** `TKT-101`", body)

        # Check files formatting
        self.assertIn("- `file1.py`: Description 1", body)
        self.assertIn("- `file2.py`: Description 2", body)

        # Check constraints formatting
        self.assertIn("- [ ] Do TDD", body)
        self.assertIn("- [ ] Avoid regression", body)

        # Check logs formatting
        self.assertIn("### 🔍 Relevant Logs / Evidence", body)
        self.assertIn("Error log details", body)
        self.assertIn("*Generated by AI Agent Studio (Orchestrator)*", body)

    def test_construct_issue_body_minimal(self):
        # Create a mock payload with minimal fields
        payload = MagicMock()
        payload.task_id = "TKT-102"
        payload.intent = "Implement feature"
        payload.context_files = {}
        payload.relevant_logs = None
        payload.constraints = []

        body = self.client._construct_issue_body(payload)

        # Assertions
        self.assertIn("@test-jules **Action Required**", body)
        self.assertIn("### 🎯 Intent\nImplement feature", body)
        self.assertIn("**Task ID:** `TKT-102`", body)

        # Check files formatting (empty)
        self.assertIn("_No specific files identified._", body)

        # Check constraints formatting (empty)
        self.assertIn("_No specific constraints._", body)

        # Check logs formatting (None)
        self.assertIn("No logs provided.", body)
        self.assertIn("*Generated by AI Agent Studio (Orchestrator)*", body)

if __name__ == '__main__':
    unittest.main()
